config/routes.rb
RelogioFerias::Application.routes.draw do
  match '/' => 'vacances_calendars#show'
  match '/' => 'vacances_calendars#show', :as => 'atualizar'
end

app/models/vacances_calendar.rb
class VacancesCalendar
  
  attr_accessor :days, :hours, :minutes, :seconds
  
  def initialize()
    set_amount_of_seconds
    start_count_down
  end
  
  def set_amount_of_seconds
    @seconds = Time.utc(2013, 9, 19, 18, 00, 00).to_i - Time.now.to_i
  end
  
  def start_count_down
    calculate_seconds
    calculate_minutes
    calculate_hours
    calculate_days
  end
      
  def calculate_seconds
    set_amount_of_seconds
  end
  
  def calculate_minutes
    @minutes = @seconds /60
  end
  
  def calculate_hours
    @hours = @minutes /60
  end
  
  def calculate_days
    @days = @hours /24
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/vacances_calendars_controller.rb
class VacancesCalendarsController < ApplicationController

  def show
    @vacances_calendar = VacancesCalendar.new
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vacances_calendars_helper.rb
module VacancesCalendarsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RelogioFerias</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vacances_calendars/show.html.erb
<h1><%= "Contagem regressiva para as férias !!! " %></h1>
<p>
	<%= "Em dias #{@vacances_calendar.days}" %>
</p>

<p>
	<%= "Em horas #{@vacances_calendar.hours}" %>
</p>

<p>
	<%= "Em segundos #{@vacances_calendar.seconds}"%>
</p>

<spam>
	<%= link_to "Atualizar", atualizar_path%>
</spam>